# configs/lora.yaml

# -------------------
# File & Directory Paths
# -------------------
data:
  meta_data_path: "dataset/pili_dataset/pili_dataset.json"
  audio_data_root: "dataset/pili_dataset/audio"
  audio_latent_root: "dataset/pili_dataset/latent"

# -------------------
# Output & Logging
# -------------------
output:
  output_dir_root: "output"
  use_wandb: true
  wandb_project_name: "sao-lora"
  run_name_prefix: "sao_lora"
  checkpointing_steps: 1000
  validation_steps: 1000
  
# -------------------
# Training Parameters
# -------------------
training:
  val_ratio: 0.1
  train_batch_size: 6
  gradient_accumulation_steps: 4
  learning_rate: 6.25e-6
  weight_decay: 1.0e-3
  num_train_epochs: 10000 # The number of steps is around this value times 
  max_train_steps: 5000 # If null, calculated from num_train_epochs
  resume_from_checkpoint: null # e.g., "/path/to/checkpoint-4000"

# -------------------
# LoRA Parameters (if use_lora is true)
# -------------------
lora:
  use_lora: true
  r: 32
  alpha: 96
  target_modules: ["to_q", "to_k", "to_v", "to_out.0"]
  lora_dropout: 0.05

# -------------------
# PEFT Parameters (if use_lora is false)
# -------------------
peft:
  cross_kv: false # Only train W_k, W_v in cross-attention layers

textual_inversion:
  use_textual_inversion: true
  placeholder_token: "V*"

# -------------------
# Dataloader Parameters
# -------------------
dataloader:
  val_batch_size: 5
  num_workers: 4

# -------------------
# LR Scheduler Parameters
# -------------------
lr_scheduler:
  type: "polynomial" # Options: "linear", "cosine", "cosine_with_restarts", "polynomial", "constant", "constant_with_warmup", "piecewise_constant"
  num_warmup_steps: 100
  power: 3.0 # For polynomial scheduler
  num_cycles: 10 # For cosine_with_restarts scheduler

# -------------------
# Pipeline & Validation Parameters
# -------------------
validation:
  denoise_steps: 100
  num_samples_to_log_per_batch: 2
  prompts: # Prompts to use when val_ratio is 0
    - "A music in the style of V*."
  seconds_total: 47 # Audio duration in seconds to generate when val_ratio is 0